# Generated by Django 4.1.10 on 2023-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idEstablecimiento', models.CharField(max_length=10)),
                ('idPersona', models.CharField(max_length=10)),
            ],
        ),
    ]
