# Generated by Django 4.1.10 on 2024-05-10 06:24

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=15)),
                ('idUsuario', models.CharField(max_length=15)),
                ('fechaIngreso', models.DateField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=45)),
                ('idUsuario', models.CharField(max_length=45)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=45)),
                ('longitud', models.CharField(max_length=45)),
                ('nombreEvento', models.CharField(max_length=45)),
                ('cover', models.CharField(max_length=45)),
                ('horarios', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechaInicio', models.DateField(max_length=45)),
                ('fechaFin', models.DateField(max_length=45)),
                ('habilitarCanciones', models.CharField(max_length=45)),
                ('idEstablecimiento', models.CharField(max_length=45)),
                ('imagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListadoCanciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=15)),
                ('idAsistencia', models.CharField(max_length=15)),
                ('nombreCancion', models.CharField(max_length=300)),
                ('artista', models.CharField(max_length=300)),
                ('albun', models.CharField(max_length=300)),
                ('duracion', models.CharField(max_length=300)),
                ('linkFotoCancion', models.TextField()),
                ('fechaSolicitada', models.DateField(max_length=45)),
                ('estadoCancion', models.TextField()),
                ('linkReproductor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MegustaEstablecimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEstablecimiento', models.CharField(max_length=45)),
                ('idUsuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MegustaEventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=45)),
                ('idUsuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEstablecimiento', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('urlImagen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('tipoIdentificacion', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('imagen', models.TextField()),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=50)),
                ('idEstablecimiento', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
