# Generated by Django 4.1.10 on 2024-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=45)),
                ('longitud', models.CharField(max_length=45)),
                ('nombreEvento', models.CharField(max_length=45)),
                ('cover', models.CharField(max_length=45)),
                ('horarios', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechaInicio', models.CharField(max_length=45)),
                ('fechaFin', models.CharField(max_length=45)),
                ('habilitarCanciones', models.CharField(max_length=45)),
                ('idEstablecimiento', models.CharField(max_length=45)),
            ],
        ),
    ]
