# Generated by Django 4.1.10 on 2024-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=45)),
                ('idUsuario', models.CharField(max_length=45)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MegustaEventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEvento', models.CharField(max_length=45)),
                ('idUsuario', models.CharField(max_length=45)),
            ],
        ),
    ]
