# Generated by Django 4.1.10 on 2024-04-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comentarios_megustaeventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEstablecimiento', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('urlImagen', models.CharField(max_length=45)),
            ],
        ),
    ]
